<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5820" started-at="2019-09-16T09:29:48Z" finished-at="2019-09-16T09:29:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5820" started-at="2019-09-16T09:29:48Z" finished-at="2019-09-16T09:29:54Z">
      <class name="ApiAutomation.Meesho.Meesho.CreateUsertest">
        <test-method status="PASS" signature="setup()[pri:0, instance:ApiAutomation.Meesho.Meesho.CreateUsertest@3532ec19]" name="setup" is-config="true" duration-ms="25" started-at="2019-09-16T14:59:48Z" finished-at="2019-09-16T14:59:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="getUser(java.lang.String, java.lang.String)[pri:0, instance:ApiAutomation.Meesho.Meesho.CreateUsertest@3532ec19]" name="getUser" duration-ms="5754" started-at="2019-09-16T14:59:48Z" data-provider="userCreate" finished-at="2019-09-16T14:59:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ashish1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sdet]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ashish1] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ashish1] but found [null]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at ApiAutomation.Meesho.Meesho.ResponseValidationCreateUser.validateCreateResponse(ResponseValidationCreateUser.java:19)
	at ApiAutomation.Meesho.Meesho.CreateUsertest.getUser(CreateUsertest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUser -->
      </class> <!-- ApiAutomation.Meesho.Meesho.CreateUsertest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
